
#ifndef _CLICKPRO_H
#define	_CLICKPRO_H

#define			CLICKSTABLELIMIT		20
#define			CLICKACTIVELIMIT		40

#define			FIRSTADD				40

#define			CLICKABSOLUTE			40


#define D_LIMIT 5

#define			CLICKSTABLELIMIT_X		30
#define			CLICKSTABLELIMIT_Y		140
#define			CLICKSTABLELIMIT_Z		20

#define			CLICKACTIVELIMIT_X		(CLICKSTABLELIMIT_X+D_LIMIT)
#define			CLICKACTIVELIMIT_Y		(CLICKSTABLELIMIT_Y+D_LIMIT)
#define			CLICKACTIVELIMIT_Z		(CLICKSTABLELIMIT_Z+D_LIMIT)

unsigned char IsClick(unsigned char *clickdata);

#endif
