
#ifndef PROJECT_DEF
#define PROJECT_DEF

#define NECKMOVE_UPLIMIT (256*2.5)	// 2.5G

#define NECK_PITCH_POSITIVE_UPLIMIT (45)
#define NECK_PITCH_POSITIVE_DOWNLIMIT (5)
#define NECK_PITCH_NEGATIVE_UPLIMIT (-10)
#define NECK_PITCH_NEGATIVE_DOWNLIMIT (-70)

#define NECK_ROLL_POSITIVE_UPLIMIT (45)
#define NECK_ROLL_POSITIVE_DOWNLIMIT (5)
#define NECK_ROLL_NEGATIVE_UPLIMIT (-5)
#define NECK_ROLL_NEGATIVE_DOWNLIMIT (-45)

#define G_ACTIVE_TIMEOUT (300)	// x 0.1sec
#define STEP_ACTIVE_TIMEOUT (50)	// x 0.1sec

#define BLE_CONNECT_TIMEOUT_SET (10)	// x 1sec

#endif
